export const GET_COUNTRIES = 'GET_COUNTRIES';

export const COUNTRY_DETAIL = 'COUNTRY_DETAIL';

export const CLEAN_STATE = 'CLEAN_STATE';

export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';

export const ORDER_CARDS = 'ORDER_CARDS';

export const FILTER_CARDS = 'FILTER_CARDS';

export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES'

export const FILTER_COUNTRIES_BY_ACTIVITY = 'FILTER_COUNTRIES_BY_ACTIVITY';

export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';

export const ERROR = 'ERROR';

